### ISSUE TITLE
Problème d'ancienneté de la date d'opération 

### ISSUE THREAD

**Issue by Mariem-Babay** [icloudsolutions/ptt2attijari#15]
Bonjour à tous , j'ai essayé de résoudre le problème de la date d'opération qu'on a rencontré dans le cas d'ancienneté de la date par rapport à la date système .
Mais après cela j'ai rencontré un problème lié au Code du centre régional remettant. 
![image](https://github.com/icloudsolutions/ptt2attijari/assets/93049223/993bf132-522b-4bd1-aa0b-2f20bcde51c2)

**Comment by skipperstar02** [comment]
Le problème semble provenir de vos fichiers eux-mêmes. Certains fichiers doivent être corrompus, car j'ai exécuté le programme sur les miens et j'ai obtenu le résultat attendu
Tout ce que vous devez faire, c'est changer les dates dans les fichiers .virement et cela fonctionnera
![image_2024-07-15_082512674](https://github.com/user-attachments/assets/a896b2aa-f8ef-488d-bf3c-6addd60f7b14)
